# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cp',
            field=models.IntegerField(default=0, max_length=11, verbose_name='휴대전화'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, max_length=8, verbose_name='생년월일'),
            preserve_default=False,
        ),
    ]
