# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20171025_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cp',
            field=models.IntegerField(verbose_name='휴대전화'),
        ),
    ]
